#!/usr/local/bin/perl

=head1 NAME

README.user_data - [Web] Explanation of user_data directory in Web interfact

=head1 DESCRIPTION

For each instance of the web-interface a directory is created under this 
user_data directory.
These user directories remain in user_data directory until the processing is 
complete.
Once the processing is complete the user directory is moved to htdocs/allwords 
directory.
If an error occurs and processing is interrupted then the user directory 
remains here.

So ideally this directory should act only as a temporary residence for these 
user directories and should contain only this README.user_data.pod file.

Last modified by : '$Id: README.user_data.pod,v 1.2 2008/04/10 04:12:02 tpederse Exp $'
